spring:
  application:
    name: h2-database-sample
  datasource:
      hikari:
        jdbc-url: jdbc:h2:mem:h2-test;TRACE_LEVEL_FILE=4;MODE=MySQL
        driver-class-name: org.h2.Driver
        username: sa
        password:
        maximum-pool-size: 10
  h2:
    console:
      enable: true
      path: /h2-console